### ISSUE TITLE
Problems with te_macros and sepolicy from AOSP 6.0

### ISSUE THREAD

**Issue by lizij** [seandroid-analytics/selint#2]
## Error in te_macros
I'm using this tool to analyze sepolicy files from aosp 4.1_r1 with m4 binary file from this version too.
It seems to have this error in te_macro.py plugin
```
Using default configuration file "/home/lizij/Documents/selint/config.py"...
Running plugin te_macros...
Processing "selinux_check_access(domain)" (1/25)...
Traceback (most recent call last):
  File "/home/lizij/Documents/selint/selint", line 312, in <module>
    plugins.get_plugin(plg).main(policy_slim, config)
  File "/home/lizij/Documents/selint/plugins/te_macros.py", line 347, in main
    removal_candidates.add(rule)
  File "/home/lizij/Documents/selint/setools/policyrep/symbol.py", line 41, in __hash__
    return hash(self.qpol_symbol.name(self.policy))
  File "/home/lizij/Documents/selint/setools/policyrep/qpol.py", line 868, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, qpol_avrule_t, name)
  File "/home/lizij/Documents/selint/setools/policyrep/qpol.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: name
```
## Error in sepolicy from 6.0
Use this tool to analyze sepolicy from AOSP 6.0 will report this error:
```
Using default configuration file "/home/lizij/Documents/selint/config.py"...
/home/lizij/Documents/selint/sepolicy6/domain.te":39:ERROR 'syntax error' at token '0x00005411' on line 5201:
allow domain self:unix_stream_socket { { create { { ioctl read getattr write setattr lock append bind connect getopt setopt shutdown } listen accept } } connectto };
allow domain domain:{ unix_dgram_socket unix_stream_socket } { 0x00005411 0x00005451 0x00005401 0x00005413 0x00005414 0x0000541b };
Traceback (most recent call last):
  File "/home/lizij/Documents/selint/selint", line 284, in <module>
    ALL_POLICY_FILES, args.extra_defs, load_neverallows=False)
  File "/home/lizij/Documents/selint/policysource/policy.py", line 82, in __init__
    self._policy = setools.policyrep.SELinuxPolicy(self.policyconf)
  File "/home/lizij/Documents/selint/setools/policyrep/__init__.py", line 86, in __init__
    self._load_policy(policyfile)
  File "/home/lizij/Documents/selint/setools/policyrep/__init__.py", line 119, in _load_policy
    format(filename, err))
setools.policyrep.exception.InvalidPolicy: Error opening policy file "/tmp/tmpxbzJbi/policy.conf": Invalid policy.
```
It seems like the policy conf can't be generated correctly
Hope the author could give me some advice

**Comment by Fbonazzi** [comment]
Hi,
both errors originate inside SETools and not SELint, so I can only provide limited help.

Regarding the first error, it seems that the "name" attribute of the policy you are using is invalid. This results in SETools raising an AttributeError when trying to handle it.

The second error looks like something we had happen at some point as well. The version of SETools you are using does not support hexadecimal permissions, and therefore rejects the policy as invalid. You should use a newer version of SETools which supports the functionality in your policy source files.

If these directions don't help fixing the issues you are having, I suggest asking the SETools maintainers.

**Comment by lizij** [comment]
First of all, thanks for you help. I didn't expect you could see this issue and answer my questions. It has been 2 years after all.

Recently I'm studying on your paper about SELint. It really helps me a lot on SEAndroid.

Back to these problems, I tried using setools 4.1.1 from github official repo. I followed the instruction, built it locally and then commented out the first several lines of \_\_init\_\_.py which asked me to install setool in python. But these two errors still happened. I can't imagine how you fix this problem just by using setools v4.

Could you tell me which version of AOSP and setools you ever tested all plugins successfully? Was it the right way that I utilized the official setool?

**Comment by Fbonazzi** [comment]
No problem. It's nice to know that someone is reading our papers and looking at our work. However, I have since stopped working on the topic, so I'm afraid I might have forgotten a lot of technical details.

I believe your first issue is just a mistake somewhere in your policy: it may be that the policy name is empty or invalid in some way.

The second issue depends on the compatibility of your SETools version and policy version. I don't remember in what policy version hexadecimal permissions were introduced, and I don't know if the most recent version of SETools supports them.

You have two options: you can ask the SETools maintainers about this, or you can comment all the lines containing hexadecimal permissions out of your policy. It may be the case that slightly modifying the policy in this way is not an issue for you, and this way you can quickly get it to work.

The culprit lines shouldn't be too hard to find, since hexadecimal permissions should all be in the 8-digit 0xXXXXXXXX format.

**Comment by lizij** [comment]
Thanks again for you advice. I've commented some lines in policies and all plugins except te_macros.py works well now. Could you please tell me a little more about your tested environments? I really hope to know that.
